### ISSUE TITLE
Variable seems not working.

### ISSUE THREAD

**Issue by f15gdsy** [screendriver/plugin-sass#9]
I tried 
```css
.text {
  color: red;
}
```
which works fine.

But when I tried:
```css
$red = red;
.text {
  color: $red;
}
```
It does not work.

Any ideas?
